#!/usr/bin/env python3
"""Validate and deterministically regenerate the hash-bound Python dependency lock."""

from __future__ import annotations

import argparse
import hashlib
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
INPUT = ROOT / "requirements-dev.in"
LOCK = ROOT / "requirements-dev.txt"
WORKFLOW = ROOT / ".github/workflows/validate.yml"

UV_VERSION = "0.9.11"
REGENERATE_COMMAND = "python3 .github/validate_python_dependency_lock.py --regenerate"
UV_HEADER = (
    "# This file was autogenerated by uv via the following command:\n"
    f"#    {REGENERATE_COMMAND}\n"
)

_NAME = r"[A-Za-z0-9][A-Za-z0-9._-]*"
_SOURCE_REQUIREMENT_RE = re.compile(rf"^({_NAME})(?:\[[^\]]+\])?\s*(.*)$")
_PIN_RE = re.compile(rf"^({_NAME})==([^\s\\;]+)\s*(?:\\)?$")
_HASH_RE = re.compile(r"^--hash=sha256:([0-9a-f]{64})\s*(?:\\)?$")


def normalize_name(value: str) -> str:
    return re.sub(r"[-_.]+", "-", value).lower()


def input_sha256(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def expected_header(input_text: str) -> str:
    return UV_HEADER + f"# input-sha256: {input_sha256(input_text)}\n"


def source_names(text: str) -> tuple[set[str], list[str]]:
    names: set[str] = set()
    errors: list[str] = []
    for line_number, raw in enumerate(text.splitlines(), 1):
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        if line.startswith("-") or " @ " in line or line.startswith(("git+", "http:", "https:")):
            errors.append(f"requirements-dev.in:{line_number}: unsupported dependency source")
            continue
        match = _SOURCE_REQUIREMENT_RE.fullmatch(line)
        if match is None:
            errors.append(f"requirements-dev.in:{line_number}: invalid requirement syntax")
            continue
        name = normalize_name(match.group(1))
        if name in names:
            errors.append(f"requirements-dev.in:{line_number}: duplicate direct requirement {name}")
        names.add(name)
    if not names:
        errors.append("requirements-dev.in: no direct dependencies declared")
    return names, errors


def locked_requirements(text: str) -> tuple[dict[str, tuple[str, tuple[str, ...]]], list[str]]:
    entries: dict[str, tuple[str, tuple[str, ...]]] = {}
    errors: list[str] = []
    current_name: str | None = None
    current_version: str | None = None
    current_hashes: list[str] = []

    def finish() -> None:
        nonlocal current_name, current_version, current_hashes
        if current_name is None or current_version is None:
            return
        if current_name in entries:
            errors.append(f"requirements-dev.txt: duplicate locked requirement {current_name}")
        if not current_hashes:
            errors.append(f"requirements-dev.txt: {current_name} has no SHA-256 hash")
        entries[current_name] = (current_version, tuple(current_hashes))
        current_name = None
        current_version = None
        current_hashes = []

    for line_number, raw in enumerate(text.splitlines(), 1):
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        hash_match = _HASH_RE.fullmatch(line)
        if hash_match is not None:
            if current_name is None:
                errors.append(f"requirements-dev.txt:{line_number}: orphaned SHA-256 hash")
            else:
                current_hashes.append(hash_match.group(1))
            continue
        pin_match = _PIN_RE.fullmatch(line)
        if pin_match is not None:
            finish()
            current_name = normalize_name(pin_match.group(1))
            current_version = pin_match.group(2)
            continue
        finish()
        errors.append(
            f"requirements-dev.txt:{line_number}: only exact name==version pins and SHA-256 hashes are allowed"
        )
    finish()
    if not entries:
        errors.append("requirements-dev.txt: no locked dependencies found")
    return entries, errors


def _workflow_line_index(text: str, command: str) -> int:
    for index, line in enumerate(text.splitlines()):
        if line.strip() == command:
            return index
    return -1


def validation_errors(input_text: str, lock_text: str, workflow_text: str) -> list[str]:
    errors: list[str] = []
    direct_names, source_errors = source_names(input_text)
    locked, lock_errors = locked_requirements(lock_text)
    errors.extend(source_errors)
    errors.extend(lock_errors)

    if not lock_text.startswith(expected_header(input_text)):
        errors.append("requirements-dev.txt: lock is not bound to the current requirements-dev.in digest")

    missing = sorted(direct_names - set(locked))
    if missing:
        errors.append("requirements-dev.txt: direct dependencies missing from lock: " + ", ".join(missing))

    validate_command = "run: python3 .github/validate_python_dependency_lock.py"
    hashed_install = "run: python -m pip install --require-hashes -r requirements-dev.txt"
    unhashed_install = "run: python -m pip install -r requirements-dev.txt"

    validate_index = _workflow_line_index(workflow_text, validate_command)
    install_index = _workflow_line_index(workflow_text, hashed_install)
    if validate_index < 0:
        errors.append("validate workflow: dependency lock validator is missing")
    if install_index < 0:
        errors.append("validate workflow: Python dependencies are not installed with --require-hashes")
    if _workflow_line_index(workflow_text, unhashed_install) >= 0:
        errors.append("validate workflow: unhashed requirements-dev.txt installation remains")
    if re.search(r"^\s*run:\s+.*pip install.*requirements-dev\.in(?:\s|$)", workflow_text, re.MULTILINE):
        errors.append("validate workflow: source requirements must not be installed directly")
    if validate_index >= 0 and install_index >= 0 and validate_index > install_index:
        errors.append("validate workflow: dependency lock must be validated before installation")

    return errors


def validate_repository(root: Path = ROOT) -> list[str]:
    return validation_errors(
        (root / "requirements-dev.in").read_text(encoding="utf-8"),
        (root / "requirements-dev.txt").read_text(encoding="utf-8"),
        (root / ".github/workflows/validate.yml").read_text(encoding="utf-8"),
    )


def regeneration_argv() -> tuple[str, ...]:
    return (
        "uv",
        "pip",
        "compile",
        "requirements-dev.in",
        "--python-version",
        "3.12",
        "--generate-hashes",
        "--no-emit-index-url",
        "--custom-compile-command",
        REGENERATE_COMMAND,
        "--output-file",
        "requirements-dev.txt",
    )


def regenerate_lock(root: Path = ROOT) -> None:
    try:
        version = subprocess.run(
            ["uv", "--version"],
            cwd=root,
            check=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
        ).stdout.strip()
    except FileNotFoundError as error:
        raise RuntimeError(f"uv {UV_VERSION} is required to regenerate the lock") from error
    except subprocess.CalledProcessError as error:
        raise RuntimeError("could not determine uv version") from error

    if version != f"uv {UV_VERSION}":
        raise RuntimeError(f"expected uv {UV_VERSION}, got {version or '<empty>'}")

    subprocess.run(regeneration_argv(), cwd=root, check=True)

    input_text = (root / "requirements-dev.in").read_text(encoding="utf-8")
    lock_path = root / "requirements-dev.txt"
    lock_text = lock_path.read_text(encoding="utf-8")
    if not lock_text.startswith(UV_HEADER):
        raise RuntimeError("uv produced an unexpected requirements-dev.txt header")
    lock_path.write_text(expected_header(input_text) + lock_text[len(UV_HEADER):], encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--regenerate", action="store_true", help="regenerate requirements-dev.txt with the pinned uv version")
    args = parser.parse_args(argv)

    if args.regenerate:
        try:
            regenerate_lock()
        except (RuntimeError, subprocess.CalledProcessError) as error:
            print(f"ERROR: {error}", file=sys.stderr)
            return 1

    errors = validate_repository()
    if errors:
        for error in errors:
            print(f"ERROR: {error}", file=sys.stderr)
        return 1

    locked, _ = locked_requirements(LOCK.read_text(encoding="utf-8"))
    print(f"commonworld Python dependency lock ok: {len(locked)} exact hashed packages")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
