#!/usr/bin/env python3
"""Generate browser locale authority and lifecycle-independent Wave-1 packs."""
from __future__ import annotations

import copy
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from scripts.locale_registry import ROOT, load_locale_contract
from scripts.proposal_runtime_i18n import proposal_runtime_inventory

PACK_PATH = ROOT / "assets/locales/wave1-locales.json"
REGISTRY_MODULE_PATH = ROOT / "assets/commonworld-locale-registry.mjs"
PACK_MODULE_PATH = ROOT / "assets/commonworld-wave1-locales.mjs"
CATALOG_LOCALE_DIR = ROOT / "catalog/locales"


def compact(value: object) -> str:
    return json.dumps(value, ensure_ascii=False, separators=(",", ":"))


RUNTIME_LOCALE_FIELDS = (
    "status",
    "direction",
    "surface_files",
    "native_name",
    "english_name",
    "translation_pack",
)


def runtime_locale_registry(contract: dict) -> dict[str, dict]:
    """Project governance-rich locale entries onto browser-required fields only.

    Release-evidence digests and candidate-evidence paths stay in the canonical
    contract. Embedding them in a public release asset would make the evidence
    digest affect the release id, which in turn changes the surface digests the
    evidence is meant to bind.
    """
    return {
        tag: {field: entry[field] for field in RUNTIME_LOCALE_FIELDS if field in entry}
        for tag, entry in contract["locale_registry"].items()
    }


def render_registry_module(contract: dict) -> str:
    registry = runtime_locale_registry(contract)
    decision = contract["decision"]
    released = decision["released_locales"]
    candidates = [tag for tag, entry in registry.items() if entry.get("status") == "candidate"]
    wave1 = contract["rollout"]["wave_1"]
    known = list(registry)
    data = compact(registry).replace("\u2028", "\\u2028").replace("\u2029", "\\u2029")
    return f"""// Generated by scripts/build_locale_runtime.py from docs/architecture/locale-release.contract.json. Do not edit.
function deepFreeze(value) {{
  if (value && typeof value === 'object' && !Object.isFrozen(value)) {{
    Object.freeze(value);
    for (const nested of Object.values(value)) deepFreeze(nested);
  }}
  return value;
}}

export const LOCALE_REGISTRY = deepFreeze({data});
export const KNOWN_UI_LOCALES = Object.freeze({compact(known)});
export const RELEASED_LOCALES = Object.freeze({compact(released)});
export const CANDIDATE_LOCALES = Object.freeze({compact(candidates)});
export const WAVE1_LOCALES = Object.freeze({compact(wave1)});
export const SUPPORTED_LOCALES = RELEASED_LOCALES;
export const DEFAULT_LOCALE = {json.dumps(decision['default_locale'])};
export const FALLBACK_LOCALE = {json.dumps(decision['fallback_locale'])};

function canonicalizeTag(value) {{
  const raw = String(value ?? '').trim();
  if (!/^[A-Za-z]{{2,3}}(?:-[A-Za-z]{{4}})?(?:-(?:[A-Za-z]{{2}}|[0-9]{{3}}))?$/.test(raw)) return null;
  const parts = raw.split('-');
  return parts.map((part, index) => {{
    if (index === 0) return part.toLowerCase();
    if (part.length === 4 && /^[A-Za-z]+$/.test(part)) return part[0].toUpperCase() + part.slice(1).toLowerCase();
    if (part.length === 2 && /^[A-Za-z]+$/.test(part)) return part.toUpperCase();
    return part;
  }}).join('-');
}}

export function canonicalLocaleTag(value) {{
  const canonical = canonicalizeTag(value);
  if (!canonical) return null;
  return KNOWN_UI_LOCALES.find((tag) => tag.toLowerCase() === canonical.toLowerCase()) ?? canonical;
}}

export function localeEntry(value) {{
  const canonical = canonicalLocaleTag(value);
  return canonical && Object.prototype.hasOwnProperty.call(LOCALE_REGISTRY, canonical)
    ? LOCALE_REGISTRY[canonical]
    : null;
}}

export function normalizeKnownLocale(value, fallback = DEFAULT_LOCALE) {{
  return matchRegistryLocale([value], {{
    statuses: [...new Set(KNOWN_UI_LOCALES.map((tag) => LOCALE_REGISTRY[tag].status))],
    fallback,
  }});
}}

export function normalizeReleasedLocale(value, fallback = DEFAULT_LOCALE) {{
  const canonical = canonicalLocaleTag(value);
  if (canonical && RELEASED_LOCALES.includes(canonical)) return canonical;
  const normalizedFallback = canonicalLocaleTag(fallback);
  return normalizedFallback && RELEASED_LOCALES.includes(normalizedFallback) ? normalizedFallback : DEFAULT_LOCALE;
}}

export function matchRegistryLocale(values, {{ statuses = ['released'], fallback = DEFAULT_LOCALE }} = {{}}) {{
  const allowed = KNOWN_UI_LOCALES.filter((tag) => statuses.includes(LOCALE_REGISTRY[tag].status));
  for (const value of Array.isArray(values) ? values : []) {{
    const canonical = canonicalizeTag(value);
    if (!canonical) continue;
    const exact = allowed.find((tag) => tag.toLowerCase() === canonical.toLowerCase());
    if (exact) return exact;
    const parts = canonical.split('-');
    if (parts.length >= 2 && parts[1].length === 4) {{
      const languageScript = parts.slice(0, 2).join('-').toLowerCase();
      const scriptMatch = allowed.find((tag) => tag.toLowerCase() === languageScript);
      if (scriptMatch) return scriptMatch;
    }}
    const primary = parts[0].toLowerCase();
    const primaryMatch = allowed.find((tag) => tag.split('-')[0].toLowerCase() === primary);
    if (primaryMatch) return primaryMatch;
  }}
  const normalizedFallback = canonicalLocaleTag(fallback);
  return normalizedFallback && allowed.includes(normalizedFallback) ? normalizedFallback : (allowed[0] ?? DEFAULT_LOCALE);
}}

export function localeSurfaceHref(locale, surface = 'index') {{
  const normalized = normalizeKnownLocale(locale);
  const files = LOCALE_REGISTRY[normalized]?.surface_files ?? LOCALE_REGISTRY[DEFAULT_LOCALE].surface_files;
  const relative = files[surface] ?? files.index;
  return relative === 'index.html' ? './' : `./${{relative}}`;
}}

export function localeFromSurfaceFile(fileName, fallback = DEFAULT_LOCALE) {{
  const value = String(fileName ?? '');
  for (const [tag, entry] of Object.entries(LOCALE_REGISTRY)) {{
    if (entry.surface_files && Object.values(entry.surface_files).includes(value)) return tag;
  }}
  return normalizeKnownLocale(fallback);
}}
"""


def runtime_wave1_packs(payload: dict, wave1: list[str]) -> dict[str, dict]:
    packs = copy.deepcopy(payload["locales"])
    for tag in wave1:
        path = CATALOG_LOCALE_DIR / f"{tag}.json"
        catalog = json.loads(path.read_text(encoding="utf-8"))
        projects = catalog.get("projects")
        if catalog.get("schema_version") != 1 or catalog.get("locale") != tag or not isinstance(projects, dict):
            raise ValueError(f"invalid catalog locale overlay: {path}")
        packs[tag]["catalog"] = {"projects": projects}
    return packs


def render_pack_module(locale_packs: dict[str, dict]) -> str:
    data = compact(locale_packs).replace("\u2028", "\\u2028").replace("\u2029", "\\u2029")
    return f"""// Generated by scripts/build_locale_runtime.py from Wave-1 UI packs and catalog locale overlays. Do not edit.
function deepFreeze(value) {{
  if (value && typeof value === 'object' && !Object.isFrozen(value)) {{
    Object.freeze(value);
    for (const nested of Object.values(value)) deepFreeze(nested);
  }}
  return value;
}}
export const WAVE1_LOCALE_PACKS = deepFreeze({data});
"""


def main() -> int:
    contract = load_locale_contract(ROOT / "docs/architecture/locale-release.contract.json")
    REGISTRY_MODULE_PATH.write_text(render_registry_module(contract), encoding="utf-8")
    payload = json.loads(PACK_PATH.read_text(encoding="utf-8"))
    if (
        payload.get("schema_version") != 2
        or payload.get("source_locale") != "en"
        or payload.get("wave") != "wave_1"
    ):
        raise ValueError("invalid Wave-1 locale pack")
    wave1 = list(contract["rollout"]["wave_1"])
    expected = set(wave1)
    locale_packs = payload.get("locales", {})
    if set(locale_packs) != expected:
        raise ValueError("Wave-1 pack locales do not match the rollout contract")
    runtime_keys = set(proposal_runtime_inventory())
    for tag, pack in locale_packs.items():
        runtime_messages = pack.get("proposal_runtime") if isinstance(pack, dict) else None
        if not isinstance(runtime_messages, dict) or set(runtime_messages) != runtime_keys:
            raise ValueError(f"Wave-1 proposal runtime messages are incomplete for {tag}")
    PACK_MODULE_PATH.write_text(render_pack_module(runtime_wave1_packs(payload, wave1)), encoding="utf-8")
    print("commonworld locale registry and Wave-1 locale modules generated")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
