import { createServer } from 'node:http';
import { createHash } from 'node:crypto';
import { readFile, stat, mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';
import { chromium } from 'playwright';
const ROOT=process.cwd();
const OUTPUT=path.join(ROOT,'docs/evidence/catalog-hierarchy-browser-v2.json');
const PAGE='/__catalog_hierarchy_v2_smoke__.html';
const MIME=new Map([['.html','text/html; charset=utf-8'],['.js','text/javascript; charset=utf-8'],['.mjs','text/javascript; charset=utf-8'],['.json','application/json; charset=utf-8']]);
function assert(ok,msg){if(!ok)throw new Error(msg);}
function stable(v){if(Array.isArray(v))return v.map(stable);if(!v||typeof v!=='object')return v;return Object.fromEntries(Object.keys(v).sort().map(k=>[k,stable(v[k])]));}
function canonical(v){return Buffer.from(`${JSON.stringify(stable(v))}\n`,'utf8');}
function sha(bytes){return createHash('sha256').update(bytes).digest('hex');}
function safeTarget(url){const pathname=decodeURIComponent(new URL(url,'http://127.0.0.1').pathname);const target=path.resolve(ROOT,pathname.replace(/^\/+/,''));return target===ROOT||target.startsWith(`${ROOT}${path.sep}`)?target:null;}
async function desc(pathname){assert(pathname.startsWith('/'),`invalid evidence path ${pathname}`);const target=path.resolve(ROOT,pathname.slice(1));assert(target.startsWith(`${ROOT}${path.sep}`),`path escapes root ${pathname}`);const bytes=await readFile(target);return {path:pathname,bytes:bytes.length,sha256:sha(bytes)};}
async function descs(paths){return Promise.all(paths.map(desc));}
function exact(actual,expected,label){assert(JSON.stringify(actual)===JSON.stringify(expected),`${label} request drift: ${JSON.stringify(actual)}`);}
const manifestV2=JSON.parse(await readFile(path.join(ROOT,'catalog/runtime/manifest.v2.json'),'utf8'));
const manifestV1=JSON.parse(await readFile(path.join(ROOT,'catalog/runtime/manifest.v1.json'),'utf8'));
const aggregateV2=JSON.parse(await readFile(path.join(ROOT,'catalog/runtime/aggregate.v2.json'),'utf8'));
const themeDescriptor=aggregateV2.segments.themes.find(x=>x.value_count>0);assert(themeDescriptor,'no theme segment');
const themePath=`/${themeDescriptor.url}`;
const themeSegment=JSON.parse(await readFile(path.join(ROOT,themeDescriptor.url),'utf8'));
const selectedTheme=Object.keys(themeSegment.index)[0];const expectedThemeKeys=themeSegment.index[selectedTheme];assert(expectedThemeKeys?.length,'no selectable theme');
const selectedShardKey=expectedThemeKeys[0];const indexKey=selectedShardKey.slice(0,manifestV2.shards.index_prefix_length);
const indexDescriptor=manifestV2.shards.indexes.find(x=>x.key===indexKey);assert(indexDescriptor,'missing index descriptor');
const indexPath=`/${indexDescriptor.url}`;const shardIndex=JSON.parse(await readFile(path.join(ROOT,indexDescriptor.url),'utf8'));
const leafDescriptor=shardIndex.entries.find(x=>x.key===selectedShardKey);assert(leafDescriptor,'missing leaf descriptor');const leafPath=`/${leafDescriptor.url}`;
const server=createServer(async(req,res)=>{try{const pathname=new URL(req.url??'/','http://127.0.0.1').pathname;if(pathname===PAGE){res.writeHead(200,{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store'});res.end('<!doctype html><meta charset="utf-8"><title>catalog hierarchy v2 smoke</title>');return;}const target=safeTarget(req.url??'/');if(!target||!(await stat(target)).isFile()){res.writeHead(404,{'Content-Type':'text/plain; charset=utf-8','Cache-Control':'no-store'});res.end('not found');return;}res.writeHead(200,{'Content-Type':MIME.get(path.extname(target))??'application/octet-stream','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'});res.end(await readFile(target));}catch{res.writeHead(404,{'Content-Type':'text/plain; charset=utf-8','Cache-Control':'no-store'});res.end('not found');}});
await new Promise((resolve,reject)=>{server.once('error',reject);server.listen(0,'127.0.0.1',resolve);});
const address=server.address();if(!address||typeof address==='string')throw new Error('server has no address');const base=`http://127.0.0.1:${address.port}`;const moduleUrl=`${base}/assets/commonworld-catalog-runtime.mjs`;
const browser=await chromium.launch({headless:true,args:['--enable-unsafe-swiftshader']});const page=await browser.newPage();const observed=[];
page.on('request',request=>{const url=new URL(request.url());if(url.origin===base&&url.pathname.startsWith('/catalog/runtime/'))observed.push(url.pathname);});
try{
 const response=await page.goto(`${base}${PAGE}`,{waitUntil:'domcontentloaded'});assert(response?.status()===200,`smoke HTTP ${response?.status()}`);
 let mark=observed.length;
 const rootResult=await page.evaluate(async({moduleUrl,manifestUrl})=>{const runtime=await import(moduleUrl);const platform=await runtime.loadCatalogAggregate({manifestUrl});globalThis.__cwRuntime=runtime;globalThis.__cwV2=platform;return {manifest_version:platform.manifest.version,aggregate_version:platform.aggregate.version,cutover_authorized:platform.manifest.migration_guard.cutover_authorized,rollback_manifest_url:platform.manifest.migration_guard.rollback_manifest_url};},{moduleUrl,manifestUrl:`${base}/catalog/runtime/manifest.v2.json`});
 const rootPaths=observed.slice(mark);exact(rootPaths,['/catalog/runtime/manifest.v2.json','/catalog/runtime/aggregate.v2.json'],'candidate root');assert(rootResult.manifest_version==='2.0'&&rootResult.aggregate_version==='2.0','candidate versions drift');assert(rootResult.cutover_authorized===false&&rootResult.rollback_manifest_url==='catalog/runtime/manifest.v1.json','guard drift');
 mark=observed.length;const defaultResult=await page.evaluate(async()=>{const p=await globalThis.__cwRuntime.loadCatalogAggregate();return {manifest_version:p.manifest.version,aggregate_version:p.aggregate.version};});const defaultPaths=observed.slice(mark);exact(defaultPaths,['/catalog/runtime/manifest.v1.json','/catalog/runtime/aggregate.v1.json'],'default');assert(defaultResult.manifest_version==='1.0'&&defaultResult.aggregate_version==='1.0','default not v1');
 mark=observed.length;const selectedKeys=await page.evaluate(async theme=>globalThis.__cwRuntime.selectCatalogShardKeys(globalThis.__cwV2,{themes:[theme]}),selectedTheme);const selectionPaths=observed.slice(mark);exact(selectionPaths,[themePath],'selection');assert(JSON.stringify(selectedKeys)===JSON.stringify(expectedThemeKeys),'selection key drift');
 mark=observed.length;const leafResult=await page.evaluate(async key=>{const v=await globalThis.__cwRuntime.loadCatalogShard(globalThis.__cwV2,key);return {key:v.key,record_ids:v.records.map(r=>r.id)};},selectedShardKey);const leafPaths=observed.slice(mark);exact(leafPaths,[indexPath,leafPath],'leaf');assert(leafResult.key===selectedShardKey&&leafResult.record_ids.length===leafDescriptor.entry_count,'leaf result drift');
 const original=await readFile(path.join(ROOT,themeDescriptor.url));const corrupted=Buffer.concat([original,Buffer.from(' ')]);await page.route(`${base}${themePath}`,route=>route.fulfill({status:200,contentType:'application/json; charset=utf-8',body:corrupted}));mark=observed.length;const corruption=await page.evaluate(async theme=>{try{await globalThis.__cwRuntime.selectCatalogShardKeys(globalThis.__cwV2,{themes:[theme]});return {verdict:'accepted',error:''};}catch(error){return {verdict:'rejected',error:String(error?.message??error)};}},selectedTheme);const corruptionPaths=observed.slice(mark);await page.unroute(`${base}${themePath}`);exact(corruptionPaths,[themePath],'corruption');assert(corruption.verdict==='rejected'&&/byte length mismatch|SHA-256 mismatch/u.test(corruption.error),`corruption accepted ${corruption.error}`);
 const evidence={kind:'commonworld.catalog_hierarchy_browser_evidence',version:'1.0',task_id:'COMMONWORLD-PUBLIC-GLOBE-V1-T039',browser:{engine:'chromium',version:browser.version()},runtime_module:await desc('/assets/commonworld-catalog-runtime.mjs'),source_catalog_sha256:manifestV2.source_catalog_sha256,default_runtime:{manifest_url:'catalog/runtime/manifest.v1.json',manifest_version:manifestV1.version,shard_prefix_length:manifestV1.shards.prefix_length},candidate_runtime:{manifest_url:'catalog/runtime/manifest.v2.json',manifest_version:manifestV2.version,index_prefix_length:manifestV2.shards.index_prefix_length,leaf_prefix_length:manifestV2.shards.leaf_prefix_length,cutover_authorized:manifestV2.migration_guard.cutover_authorized,rollback_manifest_url:manifestV2.migration_guard.rollback_manifest_url},scenarios:{candidate_root:{verdict:'pass',manifest_version:rootResult.manifest_version,aggregate_version:rootResult.aggregate_version,requests:await descs(rootPaths)},default_rollback:{verdict:'pass',manifest_version:defaultResult.manifest_version,aggregate_version:defaultResult.aggregate_version,requests:await descs(defaultPaths)},theme_selection:{verdict:'pass',theme:selectedTheme,segment_key:themeDescriptor.key,selected_shard_keys:selectedKeys,requests:await descs(selectionPaths)},leaf_load:{verdict:'pass',shard_key:leafResult.key,record_ids:leafResult.record_ids,requests:await descs(leafPaths)},corrupt_segment:{verdict:corruption.verdict,target_path:themePath,error:corruption.error,requests:await descs(corruptionPaths)}},decision:{browser_transfer_budget_state:'pass',runtime_catalogue_cutover_authorized:false},does_not_establish:['runtime cutover','production deployment','physical-device approval','real mobile-network latency']};
 await mkdir(path.dirname(OUTPUT),{recursive:true});await writeFile(OUTPUT,canonical(evidence));console.log(JSON.stringify({output:path.relative(ROOT,OUTPUT),browser:evidence.browser.version,state:'pass'},null,2));
}finally{await browser.close();await new Promise((resolve,reject)=>server.close(error=>error?reject(error):resolve()));}
